
repositories:
  - name: behoof4mind
    url:  https://behoof4mind.github.io/helm-charts/

releases:
  - name: traefik
    namespace: traefik
    chart: traefik/traefik
    atomic: false
#    values:
#      - service:
#          annotations:
#            - external-dns.alpha.kubernetes.io/hostname: traefik.workadventure-game.link
#            - kubernetes.io/ingress.class: traefik
#            - external-dns.alpha.kubernetes.io/target: traefik.workadventure-game.link
  - name: external-dns
    namespace: default
    chart: bitnami/external-dns
    atomic: false
    values:
      - logLevel: debug
      - registry: txt
      - txtOwnerId: workadventure-game
      - provider: aws
      - aws:
          region: us-east-2
          sources:
            - service
            - ingress
          domainFilters:
            - workadventure-game.link
          credentials:
            accessKey: MY_AWS_KEY
            secretKey: MY_AWS_SECRET
  - name: workadventure
    namespace: workadventure
    chart: behoof4mind/workadventure-chart
    version: 0.1.0
    atomic: false
    values:
      - domain: workadventure-game.link
      - back:
          ingress:
            tls: []
          service:
            type: LoadBalancer
      - front:
          ingress:
            tls: []
          service:
            type: LoadBalancer
      - pusher:
          ingress:
            tls: []
          service:
            type: LoadBalancer
      - uploader:
          ingress:
            tls: []
          service:
            type: LoadBalancer
      - maps:
          ingress:
            tls: []
          service:
            type: LoadBalancer

#  - name: jitsi
#    namespace: jitsi
#    chart: /Users/dlavrushko/Workspace/staff/workadventure-jitsi-chart
#    atomic: false
#    values:
#      - jibri:
#          environment:
#            - name: XMPP_DOMAIN
#              value: jitsi.meet
#            - name: XMPP_AUTH_DOMAIN
#              value: auth.jitsi.meet
#            - name: XMPP_INTERNAL_MUC_DOMAIN
#              value: internal-muc.jitsi.meet
#            - name: XMPP_MUC_DOMAIN
#              value: muc.jitsi.meet
#            - name: XMPP_GUEST_DOMAIN
#              value: guest.jitsi.meet
#            - name: JVB_BREWERY_MUC
#              value: jvbbrewery
#            - name: TZ
#              value: Europe/Moscow
#      - prosody:
#          environment:
#            - name: XMPP_DOMAIN
#              value: jitsi.meet
#            - name: XMPP_AUTH_DOMAIN
#              value: auth.jitsi.meet
#            - name: XMPP_INTERNAL_MUC_DOMAIN
#              value: internal-muc.jitsi.meet
#            - name: XMPP_MUC_DOMAIN
#              value: muc.jitsi.meet
#            - name: XMPP_GUEST_DOMAIN
#              value: guest.jitsi.meet
#            - name: JVB_BREWERY_MUC
#              value: jvbbrewery
#            - name: TZ
#              value: Europe/Moscow
#          service:
#            type: ClusterIp
#            annotations:
#              external-dns.alpha.kubernetes.io/hostname: proposody.jitsi.workadventure-game.link
#      - web:
#          environment:
#            - name: XMPP_DOMAIN
#              value: jitsi.meet
#            - name: XMPP_AUTH_DOMAIN
#              value: auth.jitsi.meet
#            - name: XMPP_INTERNAL_MUC_DOMAIN
#              value: internal-muc.jitsi.meet
#            - name: XMPP_MUC_DOMAIN
#              value: muc.jitsi.meet
#            - name: XMPP_GUEST_DOMAIN
#              value: guest.jitsi.meet
#            - name: JVB_BREWERY_MUC
#              value: jvbbrewery
#            - name: TZ
#              value: Europe/Moscow
#          service:
#            type: LoadBalancer
#            annotations:
#              external-dns.alpha.kubernetes.io/hostname: web.jitsi.workadventure-game.link
#      - jvb:
#          environment:
#            - name: XMPP_DOMAIN
#              value: jitsi.meet
#            - name: XMPP_AUTH_DOMAIN
#              value: auth.jitsi.meet
#            - name: XMPP_INTERNAL_MUC_DOMAIN
#              value: internal-muc.jitsi.meet
#            - name: XMPP_MUC_DOMAIN
#              value: muc.jitsi.meet
#            - name: XMPP_GUEST_DOMAIN
#              value: guest.jitsi.meet
#            - name: JVB_BREWERY_MUC
#              value: jvbbrewery
#            - name: TZ
#              value: Europe/Moscow
#          userAuth:
#            enabled: true
#            secret: "we4kl25g"
#          service:
#            annotations:
#              external-dns.alpha.kubernetes.io/hostname: jvb.jitsi.workadventure-game.link
#      - jicofo:
#          environment:
#            - name: XMPP_DOMAIN
#              value: jitsi.meet
#            - name: XMPP_AUTH_DOMAIN
#              value: auth.jitsi.meet
#            - name: XMPP_INTERNAL_MUC_DOMAIN
#              value: internal-muc.jitsi.meet
#            - name: XMPP_MUC_DOMAIN
#              value: muc.jitsi.meet
#            - name: XMPP_GUEST_DOMAIN
#              value: guest.jitsi.meet
#            - name: JVB_BREWERY_MUC
#              value: jvbbrewery
#            - name: TZ
#              value: Europe/Moscow
#          userAuth:
#            enabled: true
#            secret: "we4kl25g"
#      - webHost: web.jitsi.workadventure-game.link
