
repositories:
  - name: behoof4mind
    url:  https://behoof4mind.github.io/helm-charts
  - name: traefik
    url:  https://helm.traefik.io/traefik
  - name: bitnami
    url:  https://charts.bitnami.com/bitnami

releases:
  - name: traefik
    namespace: traefik
    chart: traefik/traefik
    atomic: false
  - name: external-dns
    namespace: default
    chart: bitnami/external-dns
    atomic: false
    values:
      - logLevel: debug
      - registry: txt
      - txtOwnerId: workadventure-game
      - provider: aws
      - aws:
          region: us-east-2
          sources:
            - service
            - ingress
          domainFilters:
            - workadventure-game.link
          credentials:
            accessKey: MY_AWS_KEY
            secretKey: MY_AWS_SECRET
  - name: workadventure
    namespace: workadventure
    chart: behoof4mind/workadventure-chart
    atomic: false
    values:
      - domain: workadventure-game.link
      - back:
          ingress:
            tls: []
          service:
            type: LoadBalancer
      - front:
          ingress:
            tls: []
          service:
            type: LoadBalancer
      - pusher:
          ingress:
            tls: []
          service:
            type: LoadBalancer
      - uploader:
          ingress:
            tls: []
          service:
            type: LoadBalancer
      - maps:
          ingress:
            tls: []
          service:
            type: LoadBalancer
